<?php

/**
 * Certificate / analytics counts by country (report labels).
 *
 * `id` = ISO 3166-1 numeric code as string (same as topojson/world-atlas
 * countries-110m.json / countries-10m.json geometry `id`, e.g. "682", "840").
 * Small territories may be absent from 110m simplification but ids stay valid for ISO joins.
 *
 * `countries` is generated from the bundled `resources/data/world-atlas/countries-110m.json`
 * plus synthetic `000` (unknown). Run `php scripts/build_map_config.php` after changing topology or legacy counts.
 *
 * Display names per locale live in `lang/{locale}/map_countries.php` for each supported language
 * (en, ar). API `Name` is an object keyed by locale code.
 *
 * `flag_url_template` uses `{alpha2}` (lowercase ISO 3166-1 alpha-2). Default is Flagcdn SVG for sharp
 * scaling on maps; override to e.g. `https://flagcdn.com/w640/{alpha2}.webp` for a fixed high-res raster.
 *
 * `countryStatistics` responses are cached for one month; bump `cache_code` to invalidate immediately.
 *
 * @see https://github.com/topojson/world-atlas
 * @see resources/data/world-atlas/countries-110m.json
 */
return [
    'flag_url_template' => 'https://flagcdn.com/{alpha2}.svg',

    /** Multiplier for log10(value + 1) when `is_value_log_multiplier` is true. */
    'value_log_multiplier' => 200,

    /** Bust `map/country-statistics` cache when country data or translations change. */
    'cache_code' => '106',

    /** When true, `Value` = round(log10(ValueRaw + 1) × value_log_multiplier); when false, `Value` = ValueRaw. */
    'is_value_log_multiplier' => false,

    'countries' => [
        // World-atlas countries-110m with ISO numeric id + synthetic `000` (unknown).
        // `376` (Israel) may be present; if absent, MapController mirrors `275` onto Israel geometry.
        // Extra ISO rows not in 110m (e.g. 048 Bahrain, 702 Singapore) included for API counts.
        ['id' => '000', 'alpha2' => null, 'value' => 32],
        ['id' => '004', 'alpha2' => 'af', 'value' => 7],
        ['id' => '008', 'alpha2' => 'al', 'value' => 0],
        ['id' => '010', 'alpha2' => 'aq', 'value' => 0],
        ['id' => '012', 'alpha2' => 'dz', 'value' => 175],
        ['id' => '024', 'alpha2' => 'ao', 'value' => 0],
        ['id' => '031', 'alpha2' => 'az', 'value' => 0],
        ['id' => '032', 'alpha2' => 'ar', 'value' => 7],
        ['id' => '036', 'alpha2' => 'au', 'value' => 33],
        ['id' => '040', 'alpha2' => 'at', 'value' => 29],
        ['id' => '044', 'alpha2' => 'bs', 'value' => 0],
        ['id' => '048', 'alpha2' => 'bh', 'value' => 639],
        ['id' => '050', 'alpha2' => 'bd', 'value' => 68],
        ['id' => '051', 'alpha2' => 'am', 'value' => 0],
        ['id' => '056', 'alpha2' => 'be', 'value' => 3],
        ['id' => '064', 'alpha2' => 'bt', 'value' => 0],
        ['id' => '068', 'alpha2' => 'bo', 'value' => 0],
        ['id' => '070', 'alpha2' => 'ba', 'value' => 0],
        ['id' => '072', 'alpha2' => 'bw', 'value' => 0],
        ['id' => '076', 'alpha2' => 'br', 'value' => 19],
        ['id' => '084', 'alpha2' => 'bz', 'value' => 0],
        ['id' => '090', 'alpha2' => 'sb', 'value' => 0],
        ['id' => '096', 'alpha2' => 'bn', 'value' => 0],
        ['id' => '100', 'alpha2' => 'bg', 'value' => 2],
        ['id' => '104', 'alpha2' => 'mm', 'value' => 7],
        ['id' => '108', 'alpha2' => 'bi', 'value' => 0],
        ['id' => '112', 'alpha2' => 'by', 'value' => 0],
        ['id' => '116', 'alpha2' => 'kh', 'value' => 5],
        ['id' => '120', 'alpha2' => 'cm', 'value' => 0],
        ['id' => '124', 'alpha2' => 'ca', 'value' => 60],
        ['id' => '140', 'alpha2' => 'cf', 'value' => 0],
        ['id' => '144', 'alpha2' => 'lk', 'value' => 0],
        ['id' => '148', 'alpha2' => 'td', 'value' => 0],
        ['id' => '152', 'alpha2' => 'cl', 'value' => 0],
        ['id' => '156', 'alpha2' => 'cn', 'value' => 403],
        ['id' => '158', 'alpha2' => 'tw', 'value' => 0],
        ['id' => '170', 'alpha2' => 'co', 'value' => 0],
        ['id' => '178', 'alpha2' => 'cg', 'value' => 0],
        ['id' => '180', 'alpha2' => 'cd', 'value' => 16],
        ['id' => '188', 'alpha2' => 'cr', 'value' => 0],
        ['id' => '191', 'alpha2' => 'hr', 'value' => 0],
        ['id' => '192', 'alpha2' => 'cu', 'value' => 0],
        ['id' => '196', 'alpha2' => 'cy', 'value' => 46],
        ['id' => '203', 'alpha2' => 'cz', 'value' => 1],
        ['id' => '204', 'alpha2' => 'bj', 'value' => 0],
        ['id' => '208', 'alpha2' => 'dk', 'value' => 33],
        ['id' => '214', 'alpha2' => 'do', 'value' => 0],
        ['id' => '218', 'alpha2' => 'ec', 'value' => 0],
        ['id' => '222', 'alpha2' => 'sv', 'value' => 0],
        ['id' => '226', 'alpha2' => 'gq', 'value' => 0],
        ['id' => '231', 'alpha2' => 'et', 'value' => 0],
        ['id' => '232', 'alpha2' => 'er', 'value' => 0],
        ['id' => '233', 'alpha2' => 'ee', 'value' => 0],
        ['id' => '238', 'alpha2' => 'fk', 'value' => 0],
        ['id' => '242', 'alpha2' => 'fj', 'value' => 0],
        ['id' => '246', 'alpha2' => 'fi', 'value' => 0],
        ['id' => '250', 'alpha2' => 'fr', 'value' => 245],
        ['id' => '260', 'alpha2' => 'tf', 'value' => 0],
        ['id' => '262', 'alpha2' => 'dj', 'value' => 0],
        ['id' => '266', 'alpha2' => 'ga', 'value' => 0],
        ['id' => '268', 'alpha2' => 'ge', 'value' => 0],
        ['id' => '270', 'alpha2' => 'gm', 'value' => 0],
        ['id' => '275', 'alpha2' => 'ps', 'value' => 3228],
        ['id' => '276', 'alpha2' => 'de', 'value' => 323],
        ['id' => '288', 'alpha2' => 'gh', 'value' => 25],
        ['id' => '300', 'alpha2' => 'gr', 'value' => 0],
        ['id' => '304', 'alpha2' => 'gl', 'value' => 0],
        ['id' => '320', 'alpha2' => 'gt', 'value' => 0],
        ['id' => '324', 'alpha2' => 'gn', 'value' => 0],
        ['id' => '328', 'alpha2' => 'gy', 'value' => 0],
        ['id' => '332', 'alpha2' => 'ht', 'value' => 0],
        ['id' => '340', 'alpha2' => 'hn', 'value' => 0],
        ['id' => '348', 'alpha2' => 'hu', 'value' => 0],
        ['id' => '352', 'alpha2' => 'is', 'value' => 0],
        ['id' => '356', 'alpha2' => 'in', 'value' => 253],
        ['id' => '360', 'alpha2' => 'id', 'value' => 5],
        ['id' => '364', 'alpha2' => 'ir', 'value' => 4],
        ['id' => '368', 'alpha2' => 'iq', 'value' => 120],
        ['id' => '372', 'alpha2' => 'ie', 'value' => 1155],
        ['id' => '376', 'alpha2' => 'il', 'value' => 167],
        ['id' => '380', 'alpha2' => 'it', 'value' => 42],
        ['id' => '384', 'alpha2' => 'ci', 'value' => 0],
        ['id' => '388', 'alpha2' => 'jm', 'value' => 0],
        ['id' => '392', 'alpha2' => 'jp', 'value' => 16],
        ['id' => '398', 'alpha2' => 'kz', 'value' => 3],
        ['id' => '400', 'alpha2' => 'jo', 'value' => 836],
        ['id' => '404', 'alpha2' => 'ke', 'value' => 0],
        ['id' => '408', 'alpha2' => 'kp', 'value' => 0],
        ['id' => '410', 'alpha2' => 'kr', 'value' => 0],
        ['id' => '414', 'alpha2' => 'kw', 'value' => 149],
        ['id' => '417', 'alpha2' => 'kg', 'value' => 4],
        ['id' => '418', 'alpha2' => 'la', 'value' => 0],
        ['id' => '422', 'alpha2' => 'lb', 'value' => 25],
        ['id' => '426', 'alpha2' => 'ls', 'value' => 0],
        ['id' => '428', 'alpha2' => 'lv', 'value' => 0],
        ['id' => '430', 'alpha2' => 'lr', 'value' => 0],
        ['id' => '434', 'alpha2' => 'ly', 'value' => 68],
        ['id' => '440', 'alpha2' => 'lt', 'value' => 0],
        ['id' => '442', 'alpha2' => 'lu', 'value' => 0],
        ['id' => '450', 'alpha2' => 'mg', 'value' => 0],
        ['id' => '454', 'alpha2' => 'mw', 'value' => 0],
        ['id' => '458', 'alpha2' => 'my', 'value' => 0],
        ['id' => '466', 'alpha2' => 'ml', 'value' => 0],
        ['id' => '478', 'alpha2' => 'mr', 'value' => 0],
        ['id' => '484', 'alpha2' => 'mx', 'value' => 8],
        ['id' => '496', 'alpha2' => 'mn', 'value' => 0],
        ['id' => '498', 'alpha2' => 'md', 'value' => 0],
        ['id' => '499', 'alpha2' => 'me', 'value' => 0],
        ['id' => '504', 'alpha2' => 'ma', 'value' => 68],
        ['id' => '508', 'alpha2' => 'mz', 'value' => 0],
        ['id' => '512', 'alpha2' => 'om', 'value' => 126],
        ['id' => '516', 'alpha2' => 'na', 'value' => 0],
        ['id' => '524', 'alpha2' => 'np', 'value' => 0],
        ['id' => '528', 'alpha2' => 'nl', 'value' => 1096],
        ['id' => '540', 'alpha2' => 'nc', 'value' => 0],
        ['id' => '548', 'alpha2' => 'vu', 'value' => 0],
        ['id' => '554', 'alpha2' => 'nz', 'value' => 0],
        ['id' => '558', 'alpha2' => 'ni', 'value' => 0],
        ['id' => '562', 'alpha2' => 'ne', 'value' => 0],
        ['id' => '566', 'alpha2' => 'ng', 'value' => 0],
        ['id' => '578', 'alpha2' => 'no', 'value' => 10],
        ['id' => '586', 'alpha2' => 'pk', 'value' => 98],
        ['id' => '591', 'alpha2' => 'pa', 'value' => 4],
        ['id' => '598', 'alpha2' => 'pg', 'value' => 0],
        ['id' => '600', 'alpha2' => 'py', 'value' => 0],
        ['id' => '604', 'alpha2' => 'pe', 'value' => 0],
        ['id' => '608', 'alpha2' => 'ph', 'value' => 3],
        ['id' => '616', 'alpha2' => 'pl', 'value' => 8],
        ['id' => '620', 'alpha2' => 'pt', 'value' => 0],
        ['id' => '624', 'alpha2' => 'gw', 'value' => 0],
        ['id' => '626', 'alpha2' => 'tl', 'value' => 0],
        ['id' => '630', 'alpha2' => 'pr', 'value' => 0],
        ['id' => '634', 'alpha2' => 'qa', 'value' => 78],
        ['id' => '642', 'alpha2' => 'ro', 'value' => 2],
        ['id' => '643', 'alpha2' => 'ru', 'value' => 10],
        ['id' => '646', 'alpha2' => 'rw', 'value' => 0],
        ['id' => '682', 'alpha2' => 'sa', 'value' => 211171],
        ['id' => '686', 'alpha2' => 'sn', 'value' => 0],
        ['id' => '688', 'alpha2' => 'rs', 'value' => 0],
        ['id' => '694', 'alpha2' => 'sl', 'value' => 0],
        ['id' => '702', 'alpha2' => 'sg', 'value' => 259],
        ['id' => '703', 'alpha2' => 'sk', 'value' => 3],
        ['id' => '704', 'alpha2' => 'vn', 'value' => 15],
        ['id' => '705', 'alpha2' => 'si', 'value' => 0],
        ['id' => '706', 'alpha2' => 'so', 'value' => 17],
        ['id' => '710', 'alpha2' => 'za', 'value' => 0],
        ['id' => '716', 'alpha2' => 'zw', 'value' => 0],
        ['id' => '724', 'alpha2' => 'es', 'value' => 3],
        ['id' => '728', 'alpha2' => 'ss', 'value' => 0],
        ['id' => '729', 'alpha2' => 'sd', 'value' => 70],
        ['id' => '732', 'alpha2' => 'eh', 'value' => 0],
        ['id' => '740', 'alpha2' => 'sr', 'value' => 0],
        ['id' => '748', 'alpha2' => 'sz', 'value' => 0],
        ['id' => '752', 'alpha2' => 'se', 'value' => 110],
        ['id' => '756', 'alpha2' => 'ch', 'value' => 27],
        ['id' => '760', 'alpha2' => 'sy', 'value' => 149],
        ['id' => '762', 'alpha2' => 'tj', 'value' => 0],
        ['id' => '764', 'alpha2' => 'th', 'value' => 7],
        ['id' => '768', 'alpha2' => 'tg', 'value' => 0],
        ['id' => '780', 'alpha2' => 'tt', 'value' => 0],
        ['id' => '784', 'alpha2' => 'ae', 'value' => 4096],
        ['id' => '788', 'alpha2' => 'tn', 'value' => 151],
        ['id' => '792', 'alpha2' => 'tr', 'value' => 121],
        ['id' => '795', 'alpha2' => 'tm', 'value' => 0],
        ['id' => '800', 'alpha2' => 'ug', 'value' => 0],
        ['id' => '804', 'alpha2' => 'ua', 'value' => 0],
        ['id' => '807', 'alpha2' => 'mk', 'value' => 0],
        ['id' => '818', 'alpha2' => 'eg', 'value' => 9501],
        ['id' => '826', 'alpha2' => 'gb', 'value' => 157],
        ['id' => '834', 'alpha2' => 'tz', 'value' => 0],
        ['id' => '840', 'alpha2' => 'us', 'value' => 2386],
        ['id' => '854', 'alpha2' => 'bf', 'value' => 0],
        ['id' => '858', 'alpha2' => 'uy', 'value' => 0],
        ['id' => '860', 'alpha2' => 'uz', 'value' => 0],
        ['id' => '862', 'alpha2' => 've', 'value' => 0],
        ['id' => '887', 'alpha2' => 'ye', 'value' => 44],
        ['id' => '894', 'alpha2' => 'zm', 'value' => 0],
    ],
];
